### ISSUE TITLE
Morning Review

### ISSUE THREAD

**Issue by huseyinbiyik** [BouaikIlham/Leaderboard#4]
This is a brilliant project that functioning very well. But there slight changes need to make. Below you can find them.

-Using await attribute for twice can be redundant. Because the function you call already has await attribute.
https://github.com/BouaikIlham/Leaderboard/blob/2f03724c7dac95e1f9c772b607b3925c464fe73b/src/index.js#L20
-In the future and during the program small typos can create headaches. You might want to change "refrech" to "refresh".
https://github.com/BouaikIlham/Leaderboard/blob/2f03724c7dac95e1f9c772b607b3925c464fe73b/src/index.js#L17
-You have `console.log`left a few times on the .js folders. It seems you used them even the eslint error. You might want to change them.
https://github.com/BouaikIlham/Leaderboard/blob/2f03724c7dac95e1f9c772b607b3925c464fe73b/src/api.js#L21

Other than that, it is a beautiful project! Keep up with great work!

**Comment by BouaikIlham** [comment]
Thank you for your feedback .
